#DATA SCIENCE WEEK-1 ASSIGNMENT

##soru-1 )Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

cevap)Vektorler tek boyutludur,matrisler 2 veya daha fazla boyutu vardir

soru-2 )10 elemanli bir listeden NumPy Array’i olusturunuz.

In [1]:
import numpy as np
l=[20,21,22,23,24,25,26,27,28,29]
a=np.array(l)

In [2]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

soru-3)Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [3]:
np.zeros((10,10), dtype = 'int32') 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

soru-4)Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [5]:
np.ones((10,10), dtype = 'float32')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

soru-5)Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [6]:
np.full((10,10),9,dtype = 'int32')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

soru-6)5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [7]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

soru-7)-1 ile 1 arasinda 30 adet Array olusturunuz.

In [8]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

soru-8)0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [9]:
np.random.randint(0,30,(5,6))

array([[23, 27, 14, 28,  5, 18],
       [11, 24,  2, 16,  8, 13],
       [16,  0, 10,  5,  9,  7],
       [13, 18, 27, 26,  0,  5],
       [16, 15, 19, 12,  3, 17]])

soru-9)Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

soru-10)	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
      a)	eleman sayisini
      b)	boyut bilgisini/sayisini
      c)	satir X sutun bilgisini
      d)	veri tipini numpy metodlariyla yazdiriniz.


In [13]:
k=np.random.randint(0,10,(5,10),dtype = 'int32')
k.size

50

In [14]:
k.ndim

2

In [15]:
k.shape

(5, 10)

In [16]:
k.dtype

dtype('int32')

soru-11)0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 

In [17]:
np.random.randint(10, size = (3,4,7))

array([[[5, 6, 2, 3, 5, 5, 3],
        [0, 1, 2, 0, 8, 1, 3],
        [9, 2, 0, 9, 1, 5, 0],
        [8, 9, 8, 9, 1, 0, 6]],

       [[4, 5, 4, 0, 6, 1, 7],
        [9, 2, 9, 5, 4, 6, 7],
        [3, 4, 1, 3, 3, 5, 0],
        [1, 8, 0, 6, 7, 7, 9]],

       [[1, 2, 0, 5, 7, 7, 7],
        [9, 2, 2, 8, 3, 9, 8],
        [7, 0, 6, 5, 0, 6, 6],
        [7, 3, 1, 1, 1, 5, 2]]])

soru-12 )Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [23]:
a=np.arange(5,25)

In [24]:
a.reshape(4,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

soru-13 )4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [25]:
x=np.arange(1,5)
y=np.arange(5,10)
z=np.arange(10,15)
t=np.arange(15,20)

In [26]:
np.concatenate([x,y,z,t])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

soru-14 )	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [28]:
h=np.arange(4,6)

In [35]:
k=np.random.randint(12,16,(2,2),dtype = 'int32')

In [32]:
h

array([4, 5])

In [36]:
k

array([[14, 13],
       [15, 15]])

In [37]:
np.vstack([h,k])

array([[ 4,  5],
       [14, 13],
       [15, 15]])

soru-15 )Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  
cevap)axis=0 satir olarak birlestirme gibi islemlerde kullanilir axis=1 ise sutun olarak  birlestirme gibi islemlerde kullanilir.

soru-16 )Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [39]:
m=np.random.randint(0,6,(2,3),dtype = 'int32')

In [41]:
n=np.random.randint(7,11,(2,2),dtype = 'int32')

In [42]:
p=np.random.randint(22,31,(3,3),dtype = 'int32')

In [43]:
np.concatenate([m,n], axis = 1)

array([[ 3,  4,  5, 10,  7],
       [ 4,  0,  4,  7,  8]])

In [45]:
np.concatenate([m,p], axis = 0)

array([[ 3,  4,  5],
       [ 4,  0,  4],
       [29, 23, 26],
       [22, 28, 27],
       [30, 30, 26]])

soru-17 )10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [46]:
a=[101,102,103,104,105,106,107,108,109,110]

In [47]:
np.split(a,[3,6,8])

[array([101, 102, 103]),
 array([104, 105, 106]),
 array([107, 108]),
 array([109, 110])]

soru-18 )Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [2]:
d=np.random.randint(11,32,(20,),dtype = 'int32')

In [3]:
np.sort(d)

array([11, 13, 13, 14, 14, 15, 16, 16, 17, 18, 18, 19, 21, 23, 23, 23, 25,
       26, 27, 30])

In [5]:
import numpy as np
w=np.sort(d)[::-1]    

In [7]:
w[19]

11

In [15]:
w[0]

30

soru-19 )20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin

In [57]:
g=np.random.randint(0,20,(20,),dtype = 'int32')

In [58]:
take_it=[3,5,7]

In [59]:
g[take_it]

array([17,  2,  7])

soru-20 )10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz

In [60]:
c=np.random.randint(0,20,(20,),dtype = 'int32')

In [61]:
c

array([17, 11,  7,  5, 10, 10,  0, 15, 19,  8,  7, 16, 10,  9, 15, 14, 11,
       11,  7,  0])

In [62]:
c[4]=199

In [63]:
c

array([ 17,  11,   7,   5, 199,  10,   0,  15,  19,   8,   7,  16,  10,
         9,  15,  14,  11,  11,   7,   0])

soru-21) “Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise diagonal matrix denir.Trace matrix ise bu asal kosegen ustundeki elemanlarin toplamidir.

soru-22 ) 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [6]:
import numpy as np
x = np.arange(9).reshape((3,3))

In [7]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.diag(x)

array([0, 4, 8])

In [9]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [11]:
np.diag(np.diag(x))[0,0]

0

In [12]:
np.diag(np.diag(x))[1,1]

4

In [13]:
np.diag(np.diag(x))[2,2]

8

soru-23) 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [65]:
r=np.random.randint(0,20,(10,),dtype = 'int32')

In [66]:
r

array([15, 17,  7,  1,  8, 19, 15, 10,  4, 17,  7,  7, 11, 12, 17, 11,  8,
        2, 12,  7])

In [67]:
r[3:]

array([ 1,  8, 19, 15, 10,  4, 17,  7,  7, 11, 12, 17, 11,  8,  2, 12,  7])

soru-24 )10X10 luk bir matris olusturunuz ve ;
 .	3.satir ve 5.sutuna ulasiniz.
a)5.sutunun tum satirlarina ulasiniz.
b)Tum sutunlarin 2.satirlarina ulasiniz.
c)tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
d)satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
e)satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
f)sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
g)5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 



In [68]:
f=np.random.randint(0,100,(10,10),dtype = 'int32')

In [69]:
f

array([[30, 22, 49,  8, 47, 88, 64, 54,  6, 10],
       [ 8, 12, 63, 35, 60, 79, 47, 52,  2,  8],
       [81, 75, 83,  0, 54, 75, 53, 13, 59, 94],
       [60,  6, 61, 86,  3, 95, 47, 25, 24,  2],
       [ 7, 93, 85,  7, 90, 85, 36, 83, 38, 17],
       [39, 67, 80, 12, 64, 88, 18, 43, 78, 27],
       [90, 67, 52, 10,  2, 40, 36, 68, 44, 67],
       [96, 26, 27, 74, 60, 71, 19, 26, 65, 93],
       [ 2, 96, 20, 82, 81, 92, 50, 26, 74, 55],
       [36, 58,  6, 89,  9, 41, 75, 43, 80, 72]])

In [73]:
f[2,4]  

54

In [74]:
f[:,4]

array([47, 60, 54,  3, 90, 64,  2, 60, 81,  9])

In [75]:
f[1,:]

array([ 8, 12, 63, 35, 60, 79, 47, 52,  2,  8])

In [76]:
f[2:7,:]

array([[81, 75, 83,  0, 54, 75, 53, 13, 59, 94],
       [60,  6, 61, 86,  3, 95, 47, 25, 24,  2],
       [ 7, 93, 85,  7, 90, 85, 36, 83, 38, 17],
       [39, 67, 80, 12, 64, 88, 18, 43, 78, 27],
       [90, 67, 52, 10,  2, 40, 36, 68, 44, 67]])

In [77]:
f[2:5,3:7]

array([[ 0, 54, 75, 53],
       [86,  3, 95, 47],
       [ 7, 90, 85, 36]])

In [78]:
f[5:,:4]

array([[39, 67, 80, 12],
       [90, 67, 52, 10],
       [96, 26, 27, 74],
       [ 2, 96, 20, 82],
       [36, 58,  6, 89]])

In [81]:
f[:,3::3]

array([[ 8, 64, 10],
       [35, 47,  8],
       [ 0, 53, 94],
       [86, 47,  2],
       [ 7, 36, 17],
       [12, 18, 27],
       [10, 36, 67],
       [74, 19, 93],
       [82, 50, 55],
       [89, 75, 72]])

In [83]:
f[5,5]=1988

In [84]:
f

array([[  30,   22,   49,    8,   47,   88,   64,   54,    6,   10],
       [   8,   12,   63,   35,   60,   79,   47,   52,    2,    8],
       [  81,   75,   83,    0,   54,   75,   53,   13,   59,   94],
       [  60,    6,   61,   86,    3,   95,   47,   25,   24,    2],
       [   7,   93,   85,    7,   90,   85,   36,   83,   38,   17],
       [  39,   67,   80,   12,   64, 1988,   18,   43,   78,   27],
       [  90,   67,   52,   10,    2,   40,   36,   68,   44,   67],
       [  96,   26,   27,   74,   60,   71,   19,   26,   65,   93],
       [   2,   96,   20,   82,   81,   92,   50,   26,   74,   55],
       [  36,   58,    6,   89,    9,   41,   75,   43,   80,   72]])

soru-25 ) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
20 den buyuk olan kac deger var.
a)30’dan kucuk kac deger var
b)icerisinde 33 gecen kac deger var
c)olusturulan arrayin tum elemanlarini 5 ile carpin.
d)olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.



In [89]:
q=np.arange(0,50,5)

In [90]:
np.sum(q>20)

5

In [91]:
np.sum(q<30)

6

In [92]:
np.sum(q==33)

0

In [93]:
5*q

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [94]:
q%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

soru-26 ) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
 .orlamasini aliniz.
a)standart sapmasini aliniz.
b)varyansini aliniz.
c)median’ini aliniz.
d)en kucuk degeri bulunuz.
e)en buyuk degeri bulunuz.



In [95]:
u = np.random.normal(0, 1, 50)

In [96]:
np.mean(u)

0.07662041637150269

In [97]:
np.std(u)

0.934444290819167

In [98]:
np.var(u)

0.8731861326445359

In [99]:
np.median(u)

0.16173813294001432

In [100]:
np.min(u)

-2.1722298528197475

In [101]:
np.max(u)

2.1945053131423307

Master odev ; 
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin.
Ve fark matrisinin diagonali,  -0.1 ile 0.1  arasinda olana kadar bu islemi tekrarlayin.
Istenilen matris bulundugunda program dursun ve  toplam kac dongunun kuruldugunu,  ne kadar sure icinde buldugunu ve  istenilen  matrisi  print ile birlikte ekrana yazdiriniz...
Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.
Matris uretme islemini np.random.random((axb)) fonksiyonu ile yapabilirsiniz.(size kalmis) 1:30
Cuma aksamina kadar odevlerin hepsini gondermenizi rica ediyorum.
Ayrica, matris odevinin ekran goruntusunu yada ekran videosunu gruba atmanizi istiyorum. Deneme matrislerini de gonderebilirsiniz. Hepinize kolay gelsin. 


In [22]:
import numpy as np
import time
time1=time.time()
k=0
while True:
    x=np.random.random((4,4))
    y=np.random.random((4,4))
    z=x-y
    d=np.array([z[0,0],z[1,1],z[2,2],z[3,3]])
    k+=1
    if np.all((-0.1<d)&(d<0.1)):
        break
time2=time.time()
print(time2-time1,"is total time")
print(k,"loops","\n")
print(z,"---->is my matrix which we want to find","\n")
print(d,"---->is my diagonal which we want to find")

0.03199172019958496 is total time
1886 loops 

[[-0.06048031  0.19605342  0.24180369  0.57789229]
 [-0.14282596 -0.01657879  0.25317407  0.14881658]
 [ 0.88756516 -0.47451778  0.00810276  0.46186633]
 [ 0.4957812   0.21777551 -0.22795003 -0.04483722]] ---->is my matrix which we want to find 

[-0.06048031 -0.01657879  0.00810276 -0.04483722] ---->is my diagonal which we want to find


In [11]:
import numpy as np
import time
time1=time.time()
k=0
while True:
    x=np.random.random((10,10))
    y=np.random.random((10,10))
    z=x-y
    d=np.array([z[0,0],z[1,1],z[2,2],z[3,3],z[4,4],z[5,5],z[6,6],z[7,7],z[8,8],z[9,9]])
    k+=1
    if np.all((-0.1<d)&(d<0.1)):
        break
time2=time.time()
print(time2-time1,"is total time")
print(k,"loops","\n")
print(z,"---->is my matrix which we want to find","\n")
print(d,"---->is my diagonal which we want to find")

34.40997791290283 is total time
2054398 loops 

[[-1.00064636e-03 -4.40937285e-03 -2.72239040e-01 -3.93158149e-01
  -1.38131623e-01  4.28759792e-01  7.74352063e-02  3.51623901e-01
  -1.83570829e-01 -1.86576360e-01]
 [-1.73280984e-01  5.35003738e-02 -4.52431493e-01  6.24856915e-01
   4.73450523e-01  4.56823642e-02  1.26326407e-01 -5.71687614e-01
   7.13465379e-01 -2.10355847e-02]
 [ 7.27647788e-01  1.51960089e-01  1.38369002e-02  5.48854229e-01
  -1.78955934e-02  4.58773687e-01 -7.54241343e-01 -6.03919882e-01
   2.90601880e-01 -1.59990789e-01]
 [ 3.48147727e-01  6.30974114e-01 -1.55881310e-01 -3.81703237e-02
   7.49997698e-01 -3.74420125e-01  6.85342154e-01 -2.65958945e-01
  -4.36354789e-01  1.61804080e-01]
 [-4.53473360e-01  5.42698303e-01 -3.15964438e-02  6.63908875e-01
   1.50920037e-02  6.79571714e-01  4.62691722e-01  2.62056986e-01
  -5.11606288e-01 -3.68707887e-01]
 [-5.08838034e-02  5.20316416e-01 -1.60253799e-01 -2.94208827e-01
  -3.91538562e-01 -8.32187825e-02 -9.19591458e-01  

In [ ]:
import numpy as np
import time
time1=time.time()
k=0
while True:
    x=np.random.random((20,20))
    y=np.random.random((20,20))
    z=x-y
    d=np.array([z[0,0],z[1,1],z[2,2],z[3,3],z[4,4],z[5,5],z[6,6],z[7,7],z[8,8],z[9,9],z[10,10],z[11,11],z[12,12],z[13,13],z[14,14],
                z[15,15],z[16,16],z[17,17],z[18,18],z[19,19]])
    k+=1
    if np.all((-0.1<d)&(d<0.1)):
        break
time2=time.time()
print(time2-time1,"is total time")
print(k,"loops","\n")
print(z,"---->is my matrix which we want to find","\n")
print(d,"---->is my diagonal which we want to find")